### PR TITLE
[ALL] [FIX] Clean output folder before starting tests

### PR DESCRIPTION
**Pull request by Dumbldore**
Clean output folder before starting tests

- Ensure that any outdated or incomplete output data from previous test runs is removed before each new test is executed, preventing potential false positives or misleading test results
- Add a call to DatasetTestingLibrary.clean_up(target_path) at the beginning of each test method across various dataset test files

### CODE REVIEW

**Comment by Dumbldore** [comment]
One test crashes but I checked it crashes regardless of the changeTEST

**Review by A-Huli — CHANGES_REQUESTED** [review]
Please check which files in Knee Osteoarthritis are created different than the test files and what is the difference.

**Comment by Dumbldore** [comment]
@A-Huli I don't have this dataset downloaded yet, but the test fails regardless on my changes. I created this PR: https://github.com/TheLion-ai/UMIE_datasets/pull/84 with adding only 2 prints and it fails as well. I think we could then close this and repair it in another PR.

**Comment by andrekomor** [comment]
Please take a look at #86, and refactor PR description

**Comment by Dumbldore** [comment]
@andrekomor done

**Review by A-Huli — APPROVED** [review]

**Review by A-Huli — CHANGES_REQUESTED** [review]
pls add the cleanup as a separate test the same way it is added after all the tests as Andrzej suggested

**Review by A-Huli — APPROVED** [review]

**Pull request merged**
